### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [optimisemediagroup/optimise-gtm-conversion-tag#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) Error "TypeError: cannot access property of undefined." is seen while trying to run the test. Please resolve the same

![Screenshot 2020-07-16 at 1 59 53 PM](https://user-images.githubusercontent.com/53495700/87722334-c0026800-c76c-11ea-91f6-19c31129d04a.png)

**Comment by huntg** [comment]
Thanks. Issue has been resolved now. Please could you review.

**Comment by huntg** [comment]
@praveena-pappu Could you please review again. Thanks

**Comment by praveena-pappu** [comment]
Hi,

We still see the error in console when trying to run the code. Please resolve the issue.
![Screenshot 2021-10-06 12 18 05 PM](https://user-images.githubusercontent.com/53495700/136268784-ce79538e-cbf1-427f-9391-53246e9b03c2.png)
